name = "hauzral-pharmacy-pos-api"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Static assets (frontend)
[assets]
directory = "../client/dist"
binding = "ASSETS"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "pharmacy-pos-db"
database_id = "19f3ca3b-9755-435f-87c9-54260d902f59"

# Environment variables
[vars]
JWT_SECRET = "hauzral-pharmacy-pos-secret-key-2024"
