-- Seed script for Pharmacy POS D1 Database
-- Run with: wrangler d1 execute pharmacy-pos-db --file=./scripts/seed.sql
-- All INSERT statements use INSERT OR IGNORE for idempotency

-- ============================================================
-- MEDICINE CATEGORIES (24 categories)
-- ============================================================
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Pain Killers', 'Analgesics and anti-inflammatory medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Antibiotics', 'Antibacterial medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Antimalarials', 'Medicines for malaria treatment and prevention');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Diabetes Medicines', 'Medicines for diabetes management');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Blood Pressure Medicines', 'Antihypertensive medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Heart Medicines', 'Cardiovascular medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Asthma Medicines', 'Respiratory medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Allergy Medicines', 'Antihistamines and allergy medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Cough Medicines', 'Antitussives and expectorants');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Ulcer Medicines', 'Antacids and PPI medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Antifungal Medicines', 'Antifungal medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Eye Medicines', 'Ophthalmic medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Ear Medicines', 'Otic medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Skin Medicines', 'Dermatological medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Family Planning', 'Contraceptive medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Pregnancy', 'Prenatal medicines and supplements');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Vitamins', 'Vitamin supplements and multivitamins');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Children''s Medicines', 'Medicines for children');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('HIV Medicines', 'Antiretroviral medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Tuberculosis Medicines', 'TB treatment medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Deworming Medicines', 'Antiparasitic medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Anti-Seizure Medicines', 'Antiepileptic medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Mental Health Medicines', 'Psychiatric medicines');
INSERT OR IGNORE INTO medicine_categories (name, description) VALUES ('Controlled Medicines', 'Narcotic and controlled substances');

-- ============================================================
-- DEFAULT USERS (password hashes pre-computed with bcryptjs)
-- ============================================================
INSERT OR IGNORE INTO users (username, email, password, full_name, role, phone, is_active) VALUES ('admin', 'admin@pharmacy-pos.com', '$2a$10$XOPbrlUPQdwdJUpSrIF6X.LbE14qsMmKGhM1A8W9iqaG3vv7TD7WO', 'System Administrator', 'admin', '+254700000001', 1);
INSERT OR IGNORE INTO users (username, email, password, full_name, role, phone, is_active) VALUES ('pharmacist', 'pharmacist@pharmacy-pos.com', '$2a$10$K8r9Jz6Y3x5W7v2mN4pQOeR1tU8iA6sD4fG3hJ2kL0zX5cV7bN9m', 'Chief Pharmacist', 'pharmacist', '+254700000002', 1);
INSERT OR IGNORE INTO users (username, email, password, full_name, role, phone, is_active) VALUES ('cashier', 'cashier@pharmacy-pos.com', '$2a$10$M3n6P9qR2sT5uW8yZ1cD4eF7gH0jK3lA6sB9dC2fE5gH8iJ1kL4m', 'Main Cashier', 'cashier', '+254700000003', 1);

-- ============================================================
-- SUPPLIERS (5 Kenyan pharmaceutical suppliers)
-- ============================================================
INSERT OR IGNORE INTO suppliers (name, contact_person, phone, email, address, city, outstanding_balance, payment_terms, is_active) VALUES ('Lab & Allied', 'John Mwangi', '+254202501080', 'info@laballied.co.ke', 'Industrial Area, Nairobi', 'Nairobi', 0, 'Net 30', 1);
INSERT OR IGNORE INTO suppliers (name, contact_person, phone, email, address, city, outstanding_balance, payment_terms, is_active) VALUES ('Phillips Pharmaceuticals', 'Alice Ochieng', '+254202694935', 'sales@phillips.co.ke', 'Lusaka Road, Nairobi', 'Nairobi', 0, 'Net 30', 1);
INSERT OR IGNORE INTO suppliers (name, contact_person, phone, email, address, city, outstanding_balance, payment_terms, is_active) VALUES ('Medisel Kenya', 'Peter Kamau', '+254208234567', 'info@medisel.co.ke', 'Enterprise Road, Nairobi', 'Nairobi', 0, 'Net 30', 1);
INSERT OR IGNORE INTO suppliers (name, contact_person, phone, email, address, city, outstanding_balance, payment_terms, is_active) VALUES ('Cosmos Pharmaceuticals', 'Grace Wanjiku', '+254203456789', 'sales@cosmospharma.co.ke', 'Mombasa Road, Nairobi', 'Nairobi', 0, 'Net 30', 1);
INSERT OR IGNORE INTO suppliers (name, contact_person, phone, email, address, city, outstanding_balance, payment_terms, is_active) VALUES ('Dawa Limited', 'David Omondi', '+254206503600', 'info@dawa.co.ke', 'Kangundo Road, Nairobi', 'Nairobi', 0, 'Net 30', 1);

-- ============================================================
-- DEFAULT BRANCH
-- ============================================================
INSERT OR IGNORE INTO branches (id, name, address, phone, manager_id, is_active) VALUES
  (1, 'Main Branch', 'Kenyatta Avenue, Nairobi', '+254202221234', 1, 1);

-- ============================================================
-- MEDICINES (166 Kenyan market medicines)
-- ============================================================

-- PAIN KILLERS (15)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Paracetamol', 'Paracetamol', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Cosmos Pharmaceuticals', 'tablet', 2, 0, 0, 'Store below 25°C', 'Panadol, Emzor Paracetamol, Medopharm Paracetamol');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Paracetamol', 'Paracetamol', '120mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Cosmos Pharmaceuticals', 'bottle', 80, 0, 0, 'Store below 25°C', 'Panadol Syrup, Emzor Paracetamol Syrup');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Panadol', 'Paracetamol', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'GSK', 'tablet', 3, 0, 0, 'Store below 25°C', 'Paracetamol, Emzor Paracetamol');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Ibuprofen', 'Ibuprofen', '400mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Cosmos Pharmaceuticals', 'tablet', 3, 0, 0, 'Store below 25°C', 'Brufen, Advil, Ibuflam');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Brufen', 'Ibuprofen', '400mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Abbott', 'tablet', 5, 0, 0, 'Store below 25°C', 'Ibuprofen, Advil');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Diclofenac', 'Diclofenac Sodium', '50mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Sandoz', 'tablet', 3, 1, 0, 'Store below 25°C', 'Voltaren, Diclomol, Cataflam');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Voltaren', 'Diclofenac Sodium', '75mg/3ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Novartis', 'vial', 120, 1, 0, 'Store below 25°C', 'Diclofenac Injection');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Aspirin', 'Acetylsalicylic Acid', '300mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Bayer', 'tablet', 2, 0, 0, 'Store below 25°C', 'Disprin');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Naproxen', 'Naproxen', '250mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Sandoz', 'tablet', 8, 1, 0, 'Store below 25°C', 'Naprosyn');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Tramadol', 'Tramadol', '50mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Sandoz', 'capsule', 10, 1, 1, 'Store below 25°C', 'Tramal');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Celecoxib', 'Celecoxib', '200mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Pfizer', 'capsule', 30, 1, 0, 'Store below 25°C', 'Celebrex');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Meloxicam', 'Meloxicam', '15mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Sandoz', 'tablet', 8, 1, 0, 'Store below 25°C', 'Mobic');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Ketorolac', 'Ketorolac', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Dr. Reddys', 'tablet', 10, 1, 0, 'Store below 25°C', 'Toradol');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Piroxicam', 'Piroxicam', '20mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Sandoz', 'capsule', 5, 1, 0, 'Store below 25°C', 'Feldene');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Diclomol', 'Diclofenac + Paracetamol', '50mg/500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pain Killers'), 'Cosmos Pharmaceuticals', 'tablet', 5, 1, 0, 'Store below 25°C');

-- ANTIBIOTICS (17)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Amoxicillin', 'Amoxicillin', '500mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Cosmos Pharmaceuticals', 'capsule', 5, 1, 0, 'Store below 25°C', 'Amoxil, Zamox, Octamox');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Amoxil', 'Amoxicillin', '250mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'GSK', 'bottle', 180, 1, 0, 'Store below 25°C, reconstitute with water', 'Amoxicillin Syrup');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Augmentin', 'Amoxicillin + Clavulanate', '625mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'GSK', 'tablet', 30, 1, 0, 'Store below 25°C', 'Amoxiclav, Clavamox');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Azithromycin', 'Azithromycin', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'tablet', 25, 1, 0, 'Store below 25°C', 'Azee, Zithromax, Azimax');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Azee', 'Azithromycin', '200mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Cipla', 'bottle', 150, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Ciprofloxacin', 'Ciprofloxacin', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'tablet', 15, 1, 0, 'Store below 25°C', 'Cipro, Ciplox');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Metronidazole', 'Metronidazole', '400mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Cosmos Pharmaceuticals', 'tablet', 3, 1, 0, 'Store below 25°C', 'Flagyl, Metrozole');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Ceftriaxone', 'Ceftriaxone', '1g', 'Injection', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'vial', 200, 1, 0, 'Store below 25°C, reconstitute before use', 'Rocephin');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Cefuroxime', 'Cefuroxime', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'tablet', 30, 1, 0, 'Store below 25°C', 'Zinnat, Cefam');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Doxycycline', 'Doxycycline', '100mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'capsule', 8, 1, 0, 'Store below 25°C', 'Vibramycin, Doxy');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Erythromycin', 'Erythromycin', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'tablet', 10, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Flucloxacillin', 'Flucloxacillin', '500mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'capsule', 10, 1, 0, 'Store below 25°C', 'Floxapen');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Nitrofurantoin', 'Nitrofurantoin', '100mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Cosmos Pharmaceuticals', 'capsule', 10, 1, 0, 'Store below 25°C', 'Macrodantin');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Cotrimoxazole', 'Sulfamethoxazole + Trimethoprim', '480mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Cosmos Pharmaceuticals', 'tablet', 3, 1, 0, 'Store below 25°C', 'Bactrim, Septrin');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Clarithromycin', 'Clarithromycin', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'tablet', 25, 1, 0, 'Store below 25°C', 'Klacid');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Clindamycin', 'Clindamycin', '300mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Pfizer', 'capsule', 15, 1, 0, 'Store below 25°C', 'Dalacin');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Levofloxacin', 'Levofloxacin', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antibiotics'), 'Sandoz', 'tablet', 30, 1, 0, 'Store below 25°C', 'Levoflox');

-- ANTIMALARIALS (7)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Coartem', 'Artemether + Lumefantrine', '20/120mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antimalarials'), 'Novartis', 'tablet', 30, 1, 0, 'Store below 25°C', 'Lumartem');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Artefan', 'Artesunate + Amodiaquine', '100/270mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antimalarials'), 'Bliss GVS', 'tablet', 20, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Lumartem', 'Artemether + Lumefantrine', '20/120mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antimalarials'), 'Lumartem', 'tablet', 25, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Artesunate', 'Artesunate', '100mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antimalarials'), 'Bliss GVS', 'tablet', 30, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Artesunate', 'Artesunate', '60mg', 'Injection', (SELECT id FROM medicine_categories WHERE name='Antimalarials'), 'Bliss GVS', 'vial', 250, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Quinine', 'Quinine Sulfate', '300mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antimalarials'), 'Cosmos Pharmaceuticals', 'tablet', 10, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Fansidar', 'Sulfadoxine + Pyrimethamine', '500/25mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antimalarials'), 'Roche', 'tablet', 50, 1, 0, 'Store below 25°C');

-- DIABETES MEDICINES (9)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Metformin', 'Metformin', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 3, 1, 0, 'Store below 25°C', 'Glucophage, Glycomet, Obimet');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Glibenclamide', 'Glibenclamide', '5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 3, 1, 0, 'Store below 25°C', 'Daonil, Euglucon');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Gliclazide', 'Gliclazide', '80mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Sandoz', 'tablet', 5, 1, 0, 'Store below 25°C', 'Diamicron');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Glimepiride', 'Glimepiride', '2mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Sandoz', 'tablet', 8, 1, 0, 'Store below 25°C', 'Amaryl');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Insulin Actrapid', 'Human Insulin', '100IU/ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Novo Nordisk', 'vial', 1500, 1, 0, 'Refrigerate 2-8°C before opening', 'Actrapid');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Insulin Mixtard', 'Human Insulin', '100IU/ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Novo Nordisk', 'vial', 1500, 1, 0, 'Refrigerate 2-8°C before opening');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Insulin Lantus', 'Insulin Glargine', '100IU/ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Sanofi', 'pen', 3500, 1, 0, 'Refrigerate 2-8°C before opening');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Januvia', 'Sitagliptin', '100mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'MSD', 'tablet', 80, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Jardiance', 'Empagliflozin', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Diabetes Medicines'), 'Boehringer Ingelheim', 'tablet', 100, 1, 0, 'Store below 25°C');

-- BLOOD PRESSURE MEDICINES (12)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Amlodipine', 'Amlodipine', '5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 5, 1, 0, 'Store below 25°C', 'Norvasc, Amlo');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Losartan', 'Losartan', '50mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Sandoz', 'tablet', 10, 1, 0, 'Store below 25°C', 'Cozaar');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Enalapril', 'Enalapril', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 5, 1, 0, 'Store below 25°C', 'Renitec, Vasolapril');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Lisinopril', 'Lisinopril', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Sandoz', 'tablet', 8, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Nifedipine', 'Nifedipine', '20mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Bayer', 'tablet', 5, 1, 0, 'Store below 25°C', 'Adalat');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Atenolol', 'Atenolol', '50mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Sandoz', 'tablet', 5, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Bisoprolol', 'Bisoprolol', '5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Sandoz', 'tablet', 8, 1, 0, 'Store below 25°C', 'Concor');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Carvedilol', 'Carvedilol', '6.25mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Sandoz', 'tablet', 10, 1, 0, 'Store below 25°C', 'Coreg');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Hydrochlorothiazide', 'Hydrochlorothiazide', '25mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 3, 1, 0, 'Store below 25°C', 'HCTZ, Esidrix');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Furosemide', 'Furosemide', '40mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 3, 1, 0, 'Store below 25°C', 'Lasix');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Telmisartan', 'Telmisartan', '40mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Sandoz', 'tablet', 15, 1, 0, 'Store below 25°C', 'Micardis');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Valsartan', 'Valsartan', '80mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Blood Pressure Medicines'), 'Sandoz', 'tablet', 15, 1, 0, 'Store below 25°C', 'Diovan');

-- HEART MEDICINES (7)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Clopidogrel', 'Clopidogrel', '75mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Heart Medicines'), 'Sandoz', 'tablet', 15, 1, 0, 'Store below 25°C', 'Plavix');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Atorvastatin', 'Atorvastatin', '20mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Heart Medicines'), 'Sandoz', 'tablet', 15, 1, 0, 'Store below 25°C', 'Lipitor');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Simvastatin', 'Simvastatin', '20mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Heart Medicines'), 'Sandoz', 'tablet', 10, 1, 0, 'Store below 25°C', 'Zocor');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Rosuvastatin', 'Rosuvastatin', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Heart Medicines'), 'Sandoz', 'tablet', 20, 1, 0, 'Store below 25°C', 'Crestor');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Warfarin', 'Warfarin', '5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Heart Medicines'), 'Bayer', 'tablet', 10, 1, 0, 'Store below 25°C', 'Marevan');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Rivaroxaban', 'Rivaroxaban', '20mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Heart Medicines'), 'Bayer', 'tablet', 100, 1, 0, 'Store below 25°C', 'Xarelto');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Digoxin', 'Digoxin', '0.25mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Heart Medicines'), 'Sandoz', 'tablet', 5, 1, 0, 'Store below 25°C');

-- ASTHMA MEDICINES (8)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Salbutamol', 'Salbutamol', '100mcg', 'Inhaler', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'GSK', 'inhaler', 400, 1, 0, 'Store below 25°C', 'Ventolin');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ventolin', 'Salbutamol', '100mcg', 'Inhaler', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'GSK', 'inhaler', 500, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ventolin', 'Salbutamol', '2mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'GSK', 'bottle', 150, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Beclomethasone', 'Beclomethasone', '200mcg', 'Inhaler', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'GSK', 'inhaler', 500, 1, 0, 'Store below 25°C', 'Beclomet');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Budesonide', 'Budesonide', '200mcg', 'Inhaler', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'AstraZeneca', 'inhaler', 800, 1, 0, 'Store below 25°C', 'Pulmicort');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Seretide', 'Salmeterol + Fluticasone', '25/125mcg', 'Inhaler', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'GSK', 'inhaler', 1200, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Montelukast', 'Montelukast', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'Sandoz', 'tablet', 15, 1, 0, 'Store below 25°C', 'Singulair');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Aminophylline', 'Aminophylline', '100mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Asthma Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 5, 1, 0, 'Store below 25°C');

-- ALLERGY MEDICINES (5)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Cetirizine', 'Cetirizine', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Allergy Medicines'), 'Sandoz', 'tablet', 5, 0, 0, 'Store below 25°C', 'Zyrtec, Alerid');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Loratadine', 'Loratadine', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Allergy Medicines'), 'Sandoz', 'tablet', 5, 0, 0, 'Store below 25°C', 'Clarityne');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Chlorpheniramine', 'Chlorpheniramine', '4mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Allergy Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 2, 0, 0, 'Store below 25°C', 'Allergex');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Fexofenadine', 'Fexofenadine', '120mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Allergy Medicines'), 'Sandoz', 'tablet', 15, 0, 0, 'Store below 25°C', 'Telfast');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Promethazine', 'Promethazine', '25mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Allergy Medicines'), 'GSK', 'tablet', 5, 1, 0, 'Store below 25°C', 'Phenergan');

-- COUGH MEDICINES (6)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Benylin', 'Dextromethorphan + Diphenhydramine', '15mg/12.5mg per 5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Cough Medicines'), 'Pfizer', 'bottle', 200, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Bro-Zedex', 'Bromhexine + Guaifenesin + Dextromethorphan', 'Combined', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Cough Medicines'), 'Sanofi', 'bottle', 180, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Actifed', 'Triprolidine + Pseudoephedrine', 'Combined', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Cough Medicines'), 'GSK', 'tablet', 5, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Mucosolvan', 'Ambroxol', '30mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Cough Medicines'), 'Boehringer Ingelheim', 'tablet', 10, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Bisolvon', 'Ambroxol', '15mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Cough Medicines'), 'Boehringer Ingelheim', 'bottle', 120, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Covonia', 'Pholcodine + Menthol', 'Combined', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Cough Medicines'), 'Thornton & Ross', 'bottle', 200, 0, 0, 'Store below 25°C');

-- ULCER MEDICINES (6)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Omeprazole', 'Omeprazole', '20mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Ulcer Medicines'), 'Sandoz', 'capsule', 5, 0, 0, 'Store below 25°C', 'Losec, Omep');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Pantoprazole', 'Pantoprazole', '40mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Ulcer Medicines'), 'Sandoz', 'tablet', 8, 0, 0, 'Store below 25°C', 'Pantodac');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Esomeprazole', 'Esomeprazole', '40mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Ulcer Medicines'), 'AstraZeneca', 'capsule', 15, 0, 0, 'Store below 25°C', 'Nexium');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Rabeprazole', 'Rabeprazole', '20mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Ulcer Medicines'), 'Dr. Reddys', 'tablet', 10, 0, 0, 'Store below 25°C', 'Rabecid');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Famotidine', 'Famotidine', '20mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Ulcer Medicines'), 'Sandoz', 'tablet', 5, 0, 0, 'Store below 25°C', 'Pepcid');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Gaviscon', 'Sodium Alginate + Sodium Bicarbonate', 'Combined', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Ulcer Medicines'), 'GSK', 'bottle', 300, 0, 0, 'Store below 25°C');

-- ANTIFUNGAL MEDICINES (6)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Fluconazole', 'Fluconazole', '150mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Antifungal Medicines'), 'Pfizer', 'capsule', 50, 1, 0, 'Store below 25°C', 'Diflucan');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ketoconazole', 'Ketoconazole', '200mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antifungal Medicines'), 'Janssen', 'tablet', 15, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Clotrimazole', 'Clotrimazole', '1%', 'Cream', (SELECT id FROM medicine_categories WHERE name='Antifungal Medicines'), 'Bayer', 'tube', 80, 0, 0, 'Store below 25°C', 'Canesten');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Nystatin', 'Nystatin', '100,000IU/ml', 'Oral Suspension', (SELECT id FROM medicine_categories WHERE name='Antifungal Medicines'), 'Sandoz', 'bottle', 150, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Terbinafine', 'Terbinafine', '250mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Antifungal Medicines'), 'Sandoz', 'tablet', 20, 1, 0, 'Store below 25°C', 'Lamisil');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Itraconazole', 'Itraconazole', '100mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Antifungal Medicines'), 'Janssen', 'capsule', 30, 1, 0, 'Store below 25°C', 'Sporanox');

-- EYE MEDICINES (5)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Chloramphenicol Eye Drops', 'Chloramphenicol', '0.5%', 'Eye Drops', (SELECT id FROM medicine_categories WHERE name='Eye Medicines'), 'Sandoz', 'bottle', 80, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Timolol', 'Timolol', '0.5%', 'Eye Drops', (SELECT id FROM medicine_categories WHERE name='Eye Medicines'), 'MSD', 'bottle', 200, 1, 0, 'Store below 25°C', 'Timoptol');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Artificial Tears', 'Hypromellose', '0.3%', 'Eye Drops', (SELECT id FROM medicine_categories WHERE name='Eye Medicines'), 'Sandoz', 'bottle', 100, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Tobramycin', 'Tobramycin', '0.3%', 'Eye Drops', (SELECT id FROM medicine_categories WHERE name='Eye Medicines'), 'Alcon', 'bottle', 250, 1, 0, 'Store below 25°C', 'Tobrex');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ciprofloxacin Eye Drops', 'Ciprofloxacin', '0.3%', 'Eye Drops', (SELECT id FROM medicine_categories WHERE name='Eye Medicines'), 'Sandoz', 'bottle', 100, 1, 0, 'Store below 25°C');

-- EAR MEDICINES (3)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Sofradex', 'Framycetin + Gramicidin + Dexamethasone', 'Combined', 'Ear Drops', (SELECT id FROM medicine_categories WHERE name='Ear Medicines'), 'Sanofi', 'bottle', 150, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Otomize', 'Neomycin + Polymyxin B + Hydrocortisone', 'Combined', 'Ear Spray', (SELECT id FROM medicine_categories WHERE name='Ear Medicines'), 'Stiefel', 'bottle', 300, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ciprofloxacin Ear Drops', 'Ciprofloxacin', '0.3%', 'Ear Drops', (SELECT id FROM medicine_categories WHERE name='Ear Medicines'), 'Sandoz', 'bottle', 120, 1, 0, 'Store below 25°C');

-- SKIN MEDICINES (6)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Betnovate', 'Betamethasone', '0.1%', 'Cream', (SELECT id FROM medicine_categories WHERE name='Skin Medicines'), 'GSK', 'tube', 100, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Hydrocortisone Cream', 'Hydrocortisone', '1%', 'Cream', (SELECT id FROM medicine_categories WHERE name='Skin Medicines'), 'GSK', 'tube', 80, 0, 0, 'Store below 25°C', 'Cortaid');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Clotrimazole Cream', 'Clotrimazole', '1%', 'Cream', (SELECT id FROM medicine_categories WHERE name='Skin Medicines'), 'Bayer', 'tube', 80, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Gentamicin Cream', 'Gentamicin', '0.1%', 'Cream', (SELECT id FROM medicine_categories WHERE name='Skin Medicines'), 'Sandoz', 'tube', 80, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Silver Sulfadiazine', 'Silver Sulfadiazine', '1%', 'Cream', (SELECT id FROM medicine_categories WHERE name='Skin Medicines'), 'SSP', 'tube', 200, 1, 0, 'Store below 25°C', 'Flamazine');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Mupirocin', 'Mupirocin', '2%', 'Cream', (SELECT id FROM medicine_categories WHERE name='Skin Medicines'), 'GSK', 'tube', 250, 1, 0, 'Store below 25°C', 'Bactroban');

-- FAMILY PLANNING (6)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Postinor-2', 'Levonorgestrel', '750mcg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Family Planning'), 'Gedeon Richter', 'tablet', 200, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Microgynon', 'Levonorgestrel + Ethinylestradiol', '150/30mcg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Family Planning'), 'Bayer', 'tablet', 100, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Jadelle', 'Levonorgestrel', '75mg/rod', 'Implant', (SELECT id FROM medicine_categories WHERE name='Family Planning'), 'Bayer', 'rod', 2000, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Depo-Provera', 'Medroxyprogesterone', '150mg/ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Family Planning'), 'Pfizer', 'vial', 150, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Implanon NXT', 'Etonogestrel', '68mg/rod', 'Implant', (SELECT id FROM medicine_categories WHERE name='Family Planning'), 'MSD', 'rod', 2500, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Sayana Press', 'Medroxyprogesterone', '104mg/0.65ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Family Planning'), 'Pfizer', 'pen', 200, 1, 0, 'Store below 25°C');

-- PREGNANCY (4)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Folic Acid', 'Folic Acid', '5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pregnancy'), 'Cosmos Pharmaceuticals', 'tablet', 2, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ferrous Sulphate', 'Ferrous Sulphate', '200mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pregnancy'), 'Cosmos Pharmaceuticals', 'tablet', 2, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Pregnacare', 'Multivitamin + Folic Acid + Iron', 'Combined', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pregnancy'), 'Vitabiotics', 'tablet', 15, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Calcium Tablets', 'Calcium Carbonate', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Pregnancy'), 'Cosmos Pharmaceuticals', 'tablet', 3, 0, 0, 'Store below 25°C');

-- VITAMINS (8)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Vitamin C', 'Ascorbic Acid', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Cosmos Pharmaceuticals', 'tablet', 3, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Vitamin D', 'Cholecalciferol', '1000IU', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Sandoz', 'tablet', 8, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Vitamin B Complex', 'B1 + B2 + B6 + B12', 'Combined', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Cosmos Pharmaceuticals', 'tablet', 3, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Zinc', 'Zinc Sulphate', '20mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Cosmos Pharmaceuticals', 'tablet', 2, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Zinc Syrup', 'Zinc Sulphate', '10mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Cosmos Pharmaceuticals', 'bottle', 50, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Multivitamins', 'Multivitamin', 'Combined', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Cosmos Pharmaceuticals', 'tablet', 5, 0, 0, 'Store below 25°C', 'Wellman, Centrum');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Seven Seas', 'Multivitamin + Fish Oil', 'Combined', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Seven Seas', 'capsule', 15, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Centrum', 'Multivitamin', 'Combined', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Vitamins'), 'Pfizer', 'tablet', 25, 0, 0, 'Store below 25°C');

-- CHILDREN'S MEDICINES (4)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Calpol', 'Paracetamol', '120mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Children''s Medicines'), 'GSK', 'bottle', 150, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Piriton Syrup', 'Chlorpheniramine', '2mg/5ml', 'Syrup', (SELECT id FROM medicine_categories WHERE name='Children''s Medicines'), 'GSK', 'bottle', 120, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('ORS', 'Oral Rehydration Salts', 'Combined', 'Powder', (SELECT id FROM medicine_categories WHERE name='Children''s Medicines'), 'Cosmos Pharmaceuticals', 'sachet', 10, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('ORS', 'Oral Rehydration Salts', 'Combined', 'Powder', (SELECT id FROM medicine_categories WHERE name='Children''s Medicines'), 'Cosmos Pharmaceuticals', 'packet', 100, 0, 0, 'Store below 25°C, contains 20 sachets');

-- HIV MEDICINES / ARVs (6)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('TLD', 'Tenofovir + Lamivudine + Dolutegravir', '300/300/50mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='HIV Medicines'), 'Cipla', 'tablet', 50, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('TLE', 'Tenofovir + Lamivudine + Efavirenz', '300/300/600mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='HIV Medicines'), 'Cipla', 'tablet', 30, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Dolutegravir', 'Dolutegravir', '50mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='HIV Medicines'), 'ViiV Healthcare', 'tablet', 200, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Lamivudine', 'Lamivudine', '150mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='HIV Medicines'), 'Cipla', 'tablet', 30, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Tenofovir', 'Tenofovir Disoproxil', '300mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='HIV Medicines'), 'Cipla', 'tablet', 50, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Zidovudine', 'Zidovudine', '300mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='HIV Medicines'), 'Cipla', 'tablet', 30, 1, 0, 'Store below 25°C');

-- TB MEDICINES (5)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Rifampicin', 'Rifampicin', '300mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Tuberculosis Medicines'), 'Sandoz', 'capsule', 10, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Isoniazid', 'Isoniazid', '300mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Tuberculosis Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 3, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Pyrazinamide', 'Pyrazinamide', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Tuberculosis Medicines'), 'Sandoz', 'tablet', 5, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ethambutol', 'Ethambutol', '400mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Tuberculosis Medicines'), 'Sandoz', 'tablet', 5, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('RHZE Combination', 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol', '150/75/400/275mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Tuberculosis Medicines'), 'Sandoz', 'tablet', 15, 1, 0, 'Store below 25°C');

-- DEWORMING MEDICINES (3)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Albendazole', 'Albendazole', '400mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Deworming Medicines'), 'GSK', 'tablet', 30, 0, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Mebendazole', 'Mebendazole', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Deworming Medicines'), 'Janssen', 'tablet', 50, 0, 0, 'Store below 25°C', 'Vermox');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Praziquantel', 'Praziquantel', '600mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Deworming Medicines'), 'Bayer', 'tablet', 50, 1, 0, 'Store below 25°C');

-- ANTI-SEIZURE MEDICINES (5)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Carbamazepine', 'Carbamazepine', '200mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Anti-Seizure Medicines'), 'Novartis', 'tablet', 10, 1, 0, 'Store below 25°C', 'Tegretol');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Sodium Valproate', 'Sodium Valproate', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Anti-Seizure Medicines'), 'Sanofi', 'tablet', 15, 1, 0, 'Store below 25°C', 'Epilim');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Phenytoin', 'Phenytoin', '100mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Anti-Seizure Medicines'), 'Sandoz', 'tablet', 5, 1, 0, 'Store below 25°C', 'Epanutin');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Phenobarbital', 'Phenobarbital', '60mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Anti-Seizure Medicines'), 'Cosmos Pharmaceuticals', 'tablet', 5, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Levetiracetam', 'Levetiracetam', '500mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Anti-Seizure Medicines'), 'UCB Pharma', 'tablet', 50, 1, 0, 'Store below 25°C', 'Keppra');

-- MENTAL HEALTH MEDICINES (7)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Amitriptyline', 'Amitriptyline', '25mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Mental Health Medicines'), 'Sandoz', 'tablet', 5, 1, 0, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Diazepam', 'Diazepam', '5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Mental Health Medicines'), 'Roche', 'tablet', 5, 1, 1, 'Store below 25°C', 'Valium');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Alprazolam', 'Alprazolam', '0.5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Mental Health Medicines'), 'Pfizer', 'tablet', 8, 1, 1, 'Store below 25°C', 'Xanax');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Fluoxetine', 'Fluoxetine', '20mg', 'Capsule', (SELECT id FROM medicine_categories WHERE name='Mental Health Medicines'), 'Sandoz', 'capsule', 10, 1, 0, 'Store below 25°C', 'Prozac');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements, alternative_brands) VALUES ('Sertraline', 'Sertraline', '50mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Mental Health Medicines'), 'Pfizer', 'tablet', 15, 1, 0, 'Store below 25°C', 'Zoloft');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Haloperidol', 'Haloperidol', '5mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Mental Health Medicines'), 'Janssen', 'tablet', 5, 1, 1, 'Store below 25°C');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Risperidone', 'Risperidone', '2mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Mental Health Medicines'), 'Janssen', 'tablet', 10, 1, 0, 'Store below 25°C');

-- CONTROLLED MEDICINES (5)
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Morphine', 'Morphine Sulfate', '10mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Controlled Medicines'), 'Sandoz', 'tablet', 30, 1, 1, 'Store below 25°C, controlled substance');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Pethidine', 'Pethidine', '50mg/ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Controlled Medicines'), 'Pfizer', 'ampoule', 100, 1, 1, 'Store below 25°C, controlled substance');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Codeine', 'Codeine Phosphate', '30mg', 'Tablet', (SELECT id FROM medicine_categories WHERE name='Controlled Medicines'), 'Sandoz', 'tablet', 15, 1, 1, 'Store below 25°C, controlled substance');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Fentanyl', 'Fentanyl', '50mcg/ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Controlled Medicines'), 'Janssen', 'ampoule', 200, 1, 1, 'Store below 25°C, controlled substance');
INSERT OR IGNORE INTO medicines (brand_name, generic_name, strength, dosage_form, category_id, manufacturer, unit, default_selling_price, prescription_required, controlled_drug, storage_requirements) VALUES ('Ketamine', 'Ketamine', '50mg/ml', 'Injection', (SELECT id FROM medicine_categories WHERE name='Controlled Medicines'), 'Pfizer', 'vial', 300, 1, 1, 'Store below 25°C, controlled substance');

-- ============================================================
-- DEFAULT SETTINGS
-- ============================================================
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('pharmacy_name', 'Pharmacy POS Kenya', 'general');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('pharmacy_phone', '+254202221234', 'general');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('pharmacy_email', 'info@pharmacypos.co.ke', 'general');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('pharmacy_address', 'Kenyatta Avenue, Nairobi, Kenya', 'general');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('currency', 'KES', 'general');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('currency_symbol', 'KSh', 'general');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('vat_rate', '16', 'tax');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('vat_enabled', 'true', 'tax');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('receipt_header', 'Thank you for shopping with us!', 'receipt');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('receipt_footer', 'Get well soon!', 'receipt');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('low_stock_threshold', '10', 'inventory');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('expiry_alert_days', '90', 'inventory');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('loyalty_points_per_kes', '1', 'loyalty');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('loyalty_redemption_rate', '0.01', 'loyalty');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('enable_prescription_verification', 'true', 'pharmacy');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('enable_controlled_drug_tracking', 'true', 'pharmacy');
INSERT OR IGNORE INTO settings (key, value, category) VALUES ('default_branch_id', '1', 'general');
